services:
  pmbot:
    build:
      dockerfile: Dockerfile
      context: ./pmbot
    environment:
      - DEV_MODE=${DEV_MODE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_IP=${POSTGRES_IP}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - NATS_IP=${NATS_IP}
      - NATS_PORT=${NATS_PORT}
      - BOT_TOKEN=${BOT_TOKEN}
      - TEST_GUILDS=${TEST_GUILDS}
    ports:
      - 8000:8000
    volumes:
      - ./pmbot/migrations/versions:/pmbot/migrations/versions
  nats:
    image: nats
    command: -js
    ports:
      - "${NATS_PORT}:4222"
  postgres:
    image: postgres:16.4
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 3s
      retries: 3
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  pgdata: