"""fix

Revision ID: 3e2019ed96f7
Revises: 5aab0f746801
Create Date: 2025-10-16 11:54:12.816309

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3e2019ed96f7"
down_revision: Union[str, Sequence[str], None] = "5aab0f746801"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "partners", sa.Column("host_id", sa.BigInteger(), nullable=False)
    )
    op.add_column(
        "partners", sa.Column("partner_id", sa.BigInteger(), nullable=False)
    )
    op.drop_constraint(
        op.f("partners_partner_guild_id_fkey"), "partners", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("partners_host_guild_id_fkey"), "partners", type_="foreignkey"
    )
    op.create_foreign_key(None, "partners", "guilds", ["partner_id"], ["id"])
    op.create_foreign_key(None, "partners", "guilds", ["host_id"], ["id"])
    op.drop_column("partners", "partner_guild_id")
    op.drop_column("partners", "host_guild_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "partners",
        sa.Column(
            "host_guild_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "partners",
        sa.Column(
            "partner_guild_id",
            sa.BIGINT(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "partners", type_="foreignkey")
    op.drop_constraint(None, "partners", type_="foreignkey")
    op.create_foreign_key(
        op.f("partners_host_guild_id_fkey"),
        "partners",
        "guilds",
        ["host_guild_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("partners_partner_guild_id_fkey"),
        "partners",
        "guilds",
        ["partner_guild_id"],
        ["id"],
    )
    op.drop_column("partners", "partner_id")
    op.drop_column("partners", "host_id")
    # ### end Alembic commands ###
