"""Create guilds partners

Revision ID: 5aab0f746801
Revises:
Create Date: 2025-10-16 11:46:44.045252

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5aab0f746801"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guilds",
        sa.Column("guild_id", sa.Integer(), nullable=False),
        sa.Column("prm_role_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("guild_id"),
    )
    op.create_index(op.f("ix_guilds_id"), "guilds", ["id"], unique=False)
    op.create_table(
        "partners",
        sa.Column("host_guild_id", sa.BigInteger(), nullable=False),
        sa.Column("partner_guild_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["host_guild_id"],
            ["guilds.id"],
        ),
        sa.ForeignKeyConstraint(
            ["partner_guild_id"],
            ["guilds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_partners_id"), "partners", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_partners_id"), table_name="partners")
    op.drop_table("partners")
    op.drop_index(op.f("ix_guilds_id"), table_name="guilds")
    op.drop_table("guilds")
    # ### end Alembic commands ###
